name: main

on:
  push:
    branches:
      - main

jobs:
  test-and-lint:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        python-version: [3.9, 3.10, 3.11]

    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        exclude: ${{ matrix.python-version == '3.10' && matrix.os == 'ubuntu-latest' }}

    - name: Update pip
      run: |
        python -m pip install --upgrade pip

    - name: Install flake8 and unittest
      run: |
        python -m pip install flake8
        python -m pip install -U pytest

    - name: Display Python version
      run: |
        python --version

    - name: Run flake8
      run: |
        flake8

    - name: Run unittest
      run: |
        python -m unittest discover -v
